### ISSUE TITLE
Feedback on week 13 project progress for CS2113-T14-4

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113-T14-4/main#194]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [ ] A suitable deadline set [your deadline: 2019-11-13] (:exclamation:)
   * [ ] All issues in this milestone are closed(:exclamation:)
   * [ ] Milestone explicitly closed(:exclamation:)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @jasonchanwq for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T14-4/main/pull/161 https://github.com/AY1920S1-CS2113-T14-4/main/pull/115 https://github.com/AY1920S1-CS2113-T14-4/main/pull/94 https://github.com/AY1920S1-CS2113-T14-4/main/pull/161 https://github.com/AY1920S1-CS2113-T14-4/main/pull/115 https://github.com/AY1920S1-CS2113-T14-4/main/issues/98 https://github.com/AY1920S1-CS2113-T14-4/main/issues/97 https://github.com/AY1920S1-CS2113-T14-4/main/issues/80 https://github.com/AY1920S1-CS2113-T14-4/main/issues/75 https://github.com/AY1920S1-CS2113-T14-4/main/issues/59 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @chenyuheng for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T14-4/main/issues/106 https://github.com/AY1920S1-CS2113-T14-4/main/issues/79 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @auggust for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T14-4/main/issues/81 https://github.com/AY1920S1-CS2113-T14-4/main/issues/80 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @justinchia1997 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T14-4/main/issues/111 https://github.com/AY1920S1-CS2113-T14-4/main/issues/106 https://github.com/AY1920S1-CS2113-T14-4/main/issues/79 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @yuyanglin28 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113-T14-4/main/issues/79 https://github.com/AY1920S1-CS2113-T14-4/main/issues/70 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @leowweixiang

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-14 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
